In [7]:
import numpy as np

In [8]:
import numpy as np

In [9]:
a

array([0, 1, 2, 3, 4])

In [10]:
a = np.array([_ for _ in range(5)])
b = np.array([_ for _ in range(5, 0, -1)])
print(a)
print(b)
a
b

[0 1 2 3 4]
[5 4 3 2 1]


array([5, 4, 3, 2, 1])

In [11]:
print(f'{a}\n{"object type:":>12} {type(a)}\n{"data type:":>12} {a.dtype}\n{"shape:":>12} \
{a.shape}\n{"dimension:":>12} {a.ndim}\n{"array size:":>12} {a.size}')

[0 1 2 3 4]
object type: <class 'numpy.ndarray'>
  data type: int32
      shape: (5,)
  dimension: 1
 array size: 5


In [12]:
b = np.array([[[1, 2, 3, 4, 5], [8, 9, 10, 11, 12]], [[4, 5, 6, 7, 8], [10, 11, 12, 13, 14]]])

print(f'{b}\n{"object type:":>12} {type(b)}\n{"data type:":>12} {b.dtype}\n{"shape:":>12} \
{b.shape}\n{"dimension:":>12} {b.ndim}\n{"array size:":>12} {b.size}')

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
object type: <class 'numpy.ndarray'>
  data type: int32
      shape: (2, 2, 5)
  dimension: 3
 array size: 20


In [13]:
c = np.array([[[1.0, 2, 3, 4, 5], [8.0, 9, 10, 11, 12]], [[4.0, 5, 6, 7, 8], [10.0, 11, 12, 13, 14]]])

print(f'{c}\n{"object type:":>12} {type(c)}\n{"data type:":>12} {c.dtype}\n{"shape:":>12} \
{c.shape}\n{"dimension:":>12} {c.ndim}\n{"array size:":>12} {c.size}')

[[[ 1.  2.  3.  4.  5.]
  [ 8.  9. 10. 11. 12.]]

 [[ 4.  5.  6.  7.  8.]
  [10. 11. 12. 13. 14.]]]
object type: <class 'numpy.ndarray'>
  data type: float64
      shape: (2, 2, 5)
  dimension: 3
 array size: 20


In [15]:
c = np.array([[[1.0, 2, 3, 4, 5], [8.0, 9, 10, 11, 12]], [[4.0, 5, 6, 7, 8], [10.0, 11, 12, 13, 14]]])

print(f'{c}\n{"object type:":>12} {type(c)}\n{"data type:":>12} {c.dtype}\n{"shape:":>12}\
{c.shape}\n{"dimension:":>12} {c.ndim}\n{"array size:":>12} {c.size}')

[[[ 1.  2.  3.  4.  5.]
  [ 8.  9. 10. 11. 12.]]

 [[ 4.  5.  6.  7.  8.]
  [10. 11. 12. 13. 14.]]]
object type: <class 'numpy.ndarray'>
  data type: float64
      shape:(2, 2, 5)
  dimension: 3
 array size: 20


In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)

d = np.array([10, 20, 30])
e = np.array([5, 10, 15])
f = d - e
print(f)

g = np.array([1, 2, 3])
h = np.array([4, 5, 6])
i = g * h
print(i)

j = np.array([10, 20, 30])
k = np.array([2, 5, 10])
l = j / k
print(l)

[5 7 9]
[ 5 10 15]
[ 4 10 18]
[5. 4. 3.]
